### ISSUE TITLE
Release zip not available or installation instructions wrong

### ISSUE THREAD

**Issue by wzurborg** [pairofdocs/gomule-d2r#16]
README.md says:

> Download the latest release zip and unzip it to a convenient location

However, the release zip is not there, you have to go to https://gomule.sourceforge.io/ and hope they have the latest version for download. You can also find it by clicking on Tags, but that is not in the Readme.

So, either put the release zip on the release page or change the README.

I can do that if you tell me how it is intended to work.

**Comment by pairofdocs** [comment]
The latest release for `gomule-d2r` is here https://github.com/pairofdocs/gomule-d2r/releases/latest 
![image](https://user-images.githubusercontent.com/76428136/137532619-c3662b65-1a4d-4b95-84a3-bb921b91bf50.png)

Releases are also here https://github.com/pairofdocs/gomule-d2r/releases
![image](https://user-images.githubusercontent.com/76428136/137532725-fb16c228-a960-4231-98f6-97def6828ef5.png)
which have the .zips 

https://gomule.sourceforge.io/ is the official Gomule app which https://github.com/pairofdocs/gomule-d2r forked a few months ago

There are two Gomule versions for D2R

**Comment by pairofdocs** [comment]
Yes, it's a little confusing

The .zip contains the source and the .jar executable

it's just the entire repository zipped (so can also be downloaded from https://github.com/pairofdocs/gomule-d2r/archive/refs/heads/main.zip or git cloned)

I decided to put everything in the zip since the gomule.jar file needs the data folder `d2111` 
and having all the documentation + Readme is nice too
