### ISSUE TITLE
Any plan to support game's new shared stash?

### ISSUE THREAD

**Issue by DemonPaean** [pairofdocs/gomule-d2r#7]
I tried to read SharedStashSoftCoreV2.d2i and it doesnt work now.

**Comment by pairofdocs** [comment]
The ones from the alpha work.

I still have to test with the D2R-release stash files, do you have an example file? It'll be useful for testing

**Comment by DemonPaean** [comment]
Yes. Thanks god we have this software to store gem and rune. XD
[Desktop.zip](https://github.com/pairofdocs/gomule-d2r/files/7230904/Desktop.zip)

**Comment by pairofdocs** [comment]
@DemonPaean 
I added viewing D2R's shared stash in the latest code. the stash format changed since the Alpha and so viewing works at the moment, modifying the stash is disabled. The format isn't completely known and to keep peoples' items safe I made it view-only

https://github.com/pairofdocs/gomule-d2r/archive/refs/heads/main.zip

![image](https://user-images.githubusercontent.com/76428136/134828452-a0fc8be1-e6ba-4cb6-b858-4542a0192018.png)

**Comment by DemonPaean** [comment]
Yes it works now. Thank you for your work~~~

**Comment by pairofdocs** [comment]
Cheers!
